name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: canary

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Update dependencies
        run: |
          bun update
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json bun.lockb
          git diff --quiet && git diff --staged --quiet || git commit -m "chore(deps): update dependencies"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'chore(deps): update dependencies'
          body: 'This PR updates project dependencies using `bun update`.'
          branch: 'deps-update'
          base: 'main'
          labels: 'dependencies'
          commit-message: 'chore(deps): update dependencies'
          delete-branch: true